### ISSUE TITLE
[JOSS] Paper review 1

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#18] opened 2019-05-06 10:11 UTC
You will find below my initial review of the paper itself:

Title of the package:
Why "Algebraic"? It uses numerical methods and not symbolic differentiation.

First line: use `\mathbb{R}` instead of `\mathcal{R}`

Prefer `Package.jl` to Package to designate it

Second paragraph of "Summary"
"adjustment of mathematical functions to data" is also refered to as regression, which is not mentioned in the paper, while it is fundamentally the purpose of the package.

"Detection of outliers is always regarded ...". It's hard to see what the authors mean here. Without proper references backing up the statement, this seems rather vague.

"Recently, a good review", the use of "good" is subjective (what is a good review, in what context). A review of what? 

In statistics, it is common to use f(x; θ) for a function of x with parameters theta, which one tries to fit in a regression task.

In paragraph "Functionality", the equation is not homogeneous with the rest:
`ϕ(x,t)` instead of `ϕ(x;t)`, prefer ";" to indicate the separation of data and parameters.

There could be a section on the method itself, or at least more development, including on the LOVO algorithm. For instance, the method is not black-box optimization but assumes the existence of gradient, thus making it first-order. Furthermore, if gradients are not provided by users, the use of `ForwardDiff` makes it mandatory to have the function defined in a generic way (accepting any `Real` number).
Thus, how is the proposed method different from using other first-order methods (such as the ones in Optim.jl or JuliaSmoothOptimizers)? This should be detailed.

"it is obvious that its arguments [...]", avoid the use of "obvious" which is subjective, and develop what is meant here.

"Additional features" paragraph, sentence: "the distributed version is a centralized ..." is a contradiction and should be re-phrased.

This belongs to the JOSS review https://github.com/openjournals/joss-reviews/issues/1385

**Comment by evcastelani** [comment] 2019-05-06 19:21
1. [x] Title of the package: Why "Algebraic"? It uses numerical methods and not symbolic differentiation.

    The term "algebraic" refers to the type of problem solved and not to the programming techniques of the algorithm. Although it is not a common term in adjustment functions, it serves to differ from the geometric fit (geometrical fit functions). In the case of geometric fit, we are interested in minimizing the sum of deviations of the type  `|| phi (t, x) - (t_i, y_i) ||` (ie, orthogonal projection on the curve to be adjusted). In the algebraic case, we are interested in minimizing the sum of deviations of type `|| phi (t_i, x) - y_i ||`. We chose this term to make the package's name more readable.

1. [ ] First line: use \mathbb{R} instead of \mathcal{R}

    TODO: @evcastelani 

1. [ ] Prefer Package.jl to Package to designate it

    TODO: @evcastelani 

1. [ ] Second paragraph of "Summary". "adjustment of mathematical functions to data" is also referred to as regression, which is not mentioned in the paper, while it is fundamentally the purpose of the package.

   * Just change file *
   TODO: @fsobral 

1. [ ] "Detection of outliers is always regarded ...". It's hard to see what the authors mean here. Without proper references backing up the statement, this seems rather vague.

  - Mention the statistical techniques to detect and remove outliers
  - Mention paper
  - TODO: @fsobral 

1. [ ] "Recently, a good review", the use of "good" is subjective (what is a good review, in what context). A review of what?

TODO: @evcastelani 

1. [ ] In statistics, it is common to use f(x; θ) for a function of x with parameters theta, which one tries to fit in a regression task.

    TODO: @fsobral 

1. [ ] In paragraph "Functionality", the equation is not homogeneous with the rest:
ϕ(x,t) instead of ϕ(x;t), prefer ";" to indicate the separation of data and parameters.

    TODO: @fsobral 

1. [ ] There could be a section on the method itself, or at least more development, including on the LOVO algorithm. For instance, the method is not black-box optimization but assumes the existence of gradient, thus making it first-order. Furthermore, if gradients are not provided by users, the use of ForwardDiff makes it mandatory to have the function defined in a generic way (accepting any Real number).
Thus, how is the proposed method different from using other first-order methods (such as the ones in Optim.jl or JuliaSmoothOptimizers)? This should be detailed.

1. [ ] "it is obvious that its arguments [...]", avoid the use of "obvious" which is subjective, and develop what is meant here.

    TODO: @evcastelani 

1. [ ] "Additional features" paragraph, sentence: "the distributed version is a centralized ..." is a contradiction and should be re-phrased.

    TODO: @fsobral

**Comment by matbesancon** [comment] 2019-05-07 09:05
@evcastelani thanks for the answer list. For the algebraic part, putting this explanation and/or references in the paper would be useful

**Comment by matbesancon** [comment] 2019-05-07 09:06
ping me when the editions are done

**Comment by abelsiqueira** [comment] 2019-05-08 17:25
## Review

The authors implement a solver for data fitting that automatically detects outliers, based on algorithms using Lower Order-Value Optimization. The package meets the criteria for publication on JOSS, but there are a few items that should be addressed, and a few suggestions.

- What kind of optimal fitting is achieved? Seems to be least squares (for the data without the outliers), but it's worth mentioning in the summary;
- In what sense are the outliers defined? Some quantile?
- Since the problem in the example is nonlinear, it should be indicated which solver was used to solve the problem, and which starting point;
- I think that a comparison with a different fitting not so sensitive to outliers would improve the quality of the paper. Perhaps fitting with norm-1 or Huber loss.
- The releases are not being registered. The Julia register has 0.4.3, but there is a release 0.6.0 already and the docs are being updated according to the releases;
- In the first paragraph of **Additional features**: "...provided, what results in...", change "what" to "which".
- On Figure 1, move the legend to the right, use a stronger color for the data points that are not outliers, and make it black-and-white/color-blind friendly by using a different marker style for the outliers and changing line-styles (I'd remove the "True solution").

Suggestions: These can be disregarded it the authors prefer:

- In the context of regression, I find that it's clearer to use `x` and `y` for the data and `\beta` or `\theta` for the parameters being optimized. Our traditional least squares problem `min |Ax - b|^2` is usually written as `min |Xβ - y|^2`.
- I find that entering the data separately for `x` and `y` is better, e.g.
```
x = range(-1, 1, length=100)
y = 2 .+ 3x + randn(100) * 0.1
model(β, x) = β[1] + β[2] * x[1]
output = raff(model, x, y, 2) # Here
```

**Comment by fsobral** [comment] 2019-05-08 20:15
- [ ] What kind of optimal fitting is achieved? Seems to be least squares (for the data without the outliers), but it's worth mentioning in the summary;

    Maybe the question has already been answered in the new version.
    TODO: @evcastelani 

- [ ] In what sense are the outliers defined? Some quantile?

    Maybe the question has already been answered in the new version.

- [ ] Since the problem in the example is nonlinear, it should be indicated which solver was used to solve the problem, and which starting point;

    - Explicitly state the problem solved by `RAFF`.
    - Explain better here.

- [ ] I think that a comparison with a different fitting not so sensitive to outliers would improve the quality of the paper. Perhaps fitting with norm-1 or Huber loss.

    We do not think that the 1-norm would be more robust than the least squares (suppose that the errors are smaller than 1, for example). In addition, the problem would become non-differentiable and harder to solve. Moreover, one can always create a sufficiently far outlier so that the "more robust" approaches also will construct poor models. Our example was intended to show how could one benefit for *detecting* and *eliminating* outliers, which is different from simply tolerating them.

- [ ] The releases are not being registered. The Julia register has 0.4.3, but there is a release 0.6.0 already and the docs are being updated according to the releases;

  - Is there a way of doing automatically?

- [ ] In the first paragraph of **Additional features**: "...provided, what results in...", change "what" to "which".


- [ ] On Figure 1, move the legend to the right, use a stronger color for the data points that are not outliers, and make it black-and-white/color-blind friendly by using a different marker style for the outliers and changing line-styles (I'd remove the "True solution").

    TODO: @fsobral 

Suggestions: These can be disregarded it the authors prefer:

- [x] In the context of regression, I find that it's clearer to use `x` and `y` for the data and `\beta` or `\theta` for the parameters being optimized. Our traditional least squares problem `min |Ax - b|^2` is usually written as `min |Xβ - y|^2`.

- [ ] I find that entering the data separately for `x` and `y` is better, e.g.
    ```
    x = range(-1, 1, length=100)
    y = 2 .+ 3x + randn(100) * 0.1 
    model(β, x) = β[1] + β[2] * x[1]
    output = raff(model, x, y, 2) # Here
    ```

**Comment by fsobral** [comment] 2019-05-16 19:55
Dear @abelsiqueira and @matbesancon , Thank you for you valuable comments and suggestions. We have added responses to most of your comments and questions. If there is no comment, it is because it has been fully accepted.

**Comment by matbesancon** [comment] 2019-05-16 20:13
Thank you I should have time to review the changes between now and monday

**Comment by matbesancon** [comment] 2019-05-17 13:38
## Second review

### Notation
Page 2: "we can sort the set in ascending order"
The notation below is `F_{i(theta)}(theta)` while in the rest of the paper, it is `F_{i}(theta)`, I didn't see why.
For the notation again, it is counter-intuitive that the functions get re-ordered for every theta value. Because of this, it is hard to see how S_p(theta) is not differentiable (because p is still fixed, but the re-ordering of the indices switches which function is where).

### Method

"RAFF.jl" solves this limitation by implementing a voting system. It is not clear from the end of last paragraph which limitation the authors are referring to.

How is the voting system brute-force?

> "The solution which most occurs"

Solutions are not countable (two solutions are equal iff the functions yield the same image at any in any point in the domain, does that even happen with varying points?)

### Phrasing

`i.e., it solves the problem ...` "i.e." is strangely spaced.

> One of the most usual ways to solve the problem of least-squares

It would be good to emphasize "problem of non-linear least-squares", otherwise pseudo-matrix inversion would be preferred.

"master-slave implementation" --> prefer primary-worker / primary-secondary or other terms. master-slave now tends to be avoided in technical contexts.

**Comment by fsobral** [comment] 2019-05-17 17:21
> ## Second review
> ### Notation
> 
> Page 2: "we can sort the set in ascending order"
> The notation below is `F_{i(theta)}(theta)` while in the rest of the paper, it is `F_{i}(theta)`, I didn't see why.
> For the notation again, it is counter-intuitive that the functions get re-ordered for every theta value. Because of this, it is hard to see how S_p(theta) is not differentiable (because p is still fixed, but the re-ordering of the indices switches which function is where).

The LOVO function is not very easy to understand. One has to spend some time getting used to this terminology and notation. The easiest way of seeing the non differentiability of S_p(theta) is by observing that f_min(theta) = S_p(theta) for all theta, as discussed in the paragraph starting at line 15 on pg. 2. Also, f_min highlights the combinatorial spirit of the LOVO problem.

Regarding the notation, it is correct. When we write F_{i_1(theta)}(theta) we mean that it is the smallest value in the set {F_{i}(theta), i = 1, ..., m} for a given theta.  F_{i_2(theta)}(theta) is the second smallest value in the set, and so on. The procedure for obtaining this is by evaluating all F_i at theta and ordering the set {F_{i}(theta), i = 1, ..., m}. That's how the indices i_{k}(theta) are obtained. Since the values of F_i change for different values of theta, the order of the F_i's change too.

Therefore, we cannot change the notation, but we will add a small example to explain it better. We will ping you when it is finished.

> ### Method
> 
> "RAFF.jl" solves this limitation by implementing a voting system. It is not clear from the end of last paragraph which limitation the authors are referring to.
> 
> How is the voting system brute-force?
> 
> > "The solution which most occurs"
> 
> Solutions are not countable (two solutions are equal iff the functions yield the same image at any in any point in the domain, does that even happen with varying points?)

We have rephrase this paragraph to:

In this voting system, several LOVO subproblems are solved
with different values for $p$, the number of possible trusted
points. Each solution of a LOVO subproblem is associated to a vector
parameter $\theta$. The vector parameters are compared against each
other using the Euclidian distance, where small distances (using a
threshold) are considered the same solution. The parameter $\theta^*$
which most occurs among them is declared as the solution.

> ### Phrasing
> 
> `i.e., it solves the problem ...` "i.e." is strangely spaced.
> 
> > One of the most usual ways to solve the problem of least-squares
> 
> It would be good to emphasize "problem of non-linear least-squares", otherwise pseudo-matrix inversion would be preferred.
> 
> "master-slave implementation" --> prefer primary-worker / primary-secondary or other terms. master-slave now tends to be avoided in technical contexts.

Done. Thanks for the observation

**Comment by abelsiqueira** [comment] 2019-05-19 19:15
- At the end Functionality, mention that two points were manually set to be outliers.

I'm otherwise satisfied with the updates and the new version.

**Comment by fsobral** [comment] 2019-05-20 00:48
>     * At the end Functionality, mention that two points were manually set to be outliers.
> 
> 
> I'm otherwise satisfied with the updates and the new version.

You are correct. I have added the comment in the same phrase describing of the red triangles.

**Comment by fsobral** [comment] 2019-05-20 00:52
@matbesancon We have added the simple example regarding the LOVO function. I hope it becomes clearer what we mean as its non differentiability.

**Comment by matbesancon** [comment] 2019-05-23 12:23
Thanks, it looks good. Minor last thing:

> [...] therefore, can be run locally or in a cluster of computers

Shouldn't it be "on a cluster of computers"?

> used by all experimental researchers who know a little about ...

This sentence looks a bit informal and can be interpreted in different ways: is it for experimental researchers **only if** they know a little, by experimental researchers **even if** they know little about, etc.

**Comment by fsobral** [comment] 2019-05-23 19:42
> 
> Shouldn't it be "on a cluster of computers"?

Yes, you are right. Done.

> 
> > used by all experimental researchers who know a little about ...
> 
> This sentence looks a bit informal and can be interpreted in different ways: is it for experimental researchers **only if** they know a little, by experimental researchers **even if** they know little about, etc.

The idea is that they do not need to know much about mathematical modeling, but definitely, they must know something, otherwise writing Julia functions defining models won't make any sense. I have rewritten this sentence to

This package is intended to be used by any experimental researcher
with a little knowledge about mathematical modeling and fitting
functions.

**Comment by matbesancon** [comment] 2019-05-24 09:08
I'm ok with the changes thanks. Last tiny things in the reference, the letters are not properly capitalizd, you should use `title = {{Title}}` instead of `title = {Title}` everywhere

**Comment by evcastelani** [comment] 2019-05-24 13:26
Hi @matbesancon! You're right. The title of the references had to be standardized. Thanks for the note. However, running locally by Pandoc, the use of `{{tilte}}` worked like a charm but in JOSS no. In this way, I made the manual correction of capital letters to avoid possible errors.

**Comment by matbesancon** [comment] 2019-05-24 13:41
Hi, no it seems to have worked, the titles are properly capitalized. I think this was the last point on my side.
@abelsiqueira should we close this issue?

**Comment by abelsiqueira** [comment] 2019-05-24 15:12
Yes, I'm happy with the changes.

**Comment by matbesancon** [comment] 2019-05-24 15:17
Great, doing one last check on the last version of the software in an hour or so, then validating

**Comment by matbesancon** [comment] 2019-05-28 15:21
sorry last small details in "installation and usage":
"and can be directly installed from *the* Julia package repository" or "and can be directly installed from Julia's package repository" but the former might be preferred.

"All *descriptions*" or "The whole description"

**Comment by evcastelani** [comment] 2019-05-28 16:47
@matbesancon you're right. These typos have been fixed.

**Comment by matbesancon** [comment] 2019-05-28 16:49
ok great, the paper seems fine, watch out builds seem to all fail

**Comment by evcastelani** [comment] 2019-05-28 19:47
@matbesancon Ok, thanks! Now we fixed the problem and both branches (master and joss) are passing the automated tests.

**Comment by matbesancon** [comment] 2019-05-28 20:51
perfect, I think this is good on my side. @abelsiqueira do you still have something on the last version of the paper?

**Comment by abelsiqueira** [comment] 2019-05-29 16:47
Reference Keles needs to be updated (DOI, pages and author name):
```
@article{Kele2018,
  doi = {10.15345/iojes.2018.03.013},
  url = {https://doi.org/10.15345/iojes.2018.03.013},
  year = {2018},
  publisher = {International Online Journal of Educational Sciences},
  volume = {10},
  number = {3},
  author = {Taliha Kele{\c{s}}},
  title = {Comparison of Classical Least Squares and Orthogonal Regression in Measurement Error Models},
  journal = {International Online Journal of Educational Sciences}
}
```
Found the DOI on the paper and the bibtex using https://www.doi2bib.org/bib/10.15345/iojes.2018.03.013.

That's it for me.

**Comment by evcastelani** [comment] 2019-05-29 17:12
@abelsiqueira  you're right! We fixed DOI,name and pages as you suggest.

**Comment by evcastelani** [comment] 2019-05-29 17:13
@matbesancon and @abelsiqueira  Can I close this issue?

**Comment by matbesancon** [comment] 2019-05-29 17:15
If you re-built the paper with corrections from @abelsiqueira
<https://github.com/abelsiqueira> it's up to him to close, it's good on my
side

**Comment by evcastelani** [comment] 2019-05-29 17:18
@matbesancon Ok, you're right.

**Comment by abelsiqueira** [comment] 2019-05-29 17:19
Yes, close it, thanks for the corrections.

**Closed** 2019-05-29 18:14 UTC
